<?php

/**
 * @file
 * Entity Class Formatter module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldItemListInterface;

/**
 * Implements hook_entity_view_alter().
 */
function boostrap_layout_classes_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // Skip entities which are not holding fields.
  if (!($entity instanceof FieldableEntityInterface)) {
    return;
  }
  $fields = [];

  // Get fields from standard manage display form.
  foreach ($display->getComponents() as $name => $component) {

    // Only if Entity Class formatter is used.
    if (isset($component['type']) && $component['type'] === 'boostrap_layout_classes_formatter') {
      $fields[$name][] = !empty($component['settings']) ? $component['settings'] : [];
    }
  }

  // Process all discovered fields.
  foreach ($fields as $name => $settings_set) {
    if (!$entity->hasField($name)) {
      continue;
    }
    $field = $entity->get($name);

    // Apply settings of every field instance.
    foreach ($settings_set as $settings) {
      _boostrap_layout_classes_apply($build, $field, $settings);
    }
  }
}

/**
 * Applies all field values using defined settings.
 */
function _boostrap_layout_classes_apply(array &$build, FieldItemListInterface $field, array $settings) {
  $values = [];
  $field_definition = $field->getFieldDefinition();

  // Only for boolean field type.
  if ($field_definition->getType() === 'boolean') {

    // Fill configured label based on value.
    if (filter_var($field->value, FILTER_VALIDATE_BOOLEAN)) {
      $label = $field_definition->getSetting('on_label');
    }
    else {
      $label = $field_definition->getSetting('off_label');
    }
    $values[] = $label;
  }

  // For other simple fields.
  else {
    foreach ($field->getValue() as $item) {

      // Fill value if not empty.
      if (!empty($item['value'])) {

        // Split value into multiple classes when spaces are used.
        foreach (explode(' ', $item['value']) as $class) {
          $values[] = $class;
        }
      }
    }
  }

  // Process all discovered values.
  foreach ($values as $value) {
    $build['#attributes']['class'][] = Html::getClass($value);
  }
}
